---
 - name: Add azureuser to docker group
   hosts: all
   become: true
   vars:
     myusers: azureuser
     mygroups: "docker"
  
   tasks:
    - name: adding to docker group
      ansible.builtin.user:
        name: "{{myusers}}"
        groups: "{{mygroups}}"
        append: true
  

 